apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-test
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/aali309/argocd-test-nested.git'
    targetRevision: HEAD
    path: apps/rollout-test
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rollout-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
